// Build script for Truent: Compiles .sinv invariant DSL files into Rust
//
// This script:
// 1. Discovers all .sinv files in invariants/ directory
// 2. Parses and validates each .sinv file
// 3. Generates a Rust module (src/generated/invariants.rs) with InvariantDef structs
// 4. Fails the build if any .sinv file has syntax errors (with file:line info)

use std::fs;
use std::path::PathBuf;
use std::collections::BTreeMap;

fn main() {
    // Rerun if any .sinv files change
    println!("cargo:rerun-if-changed=invariants/");
    println!("cargo:rerun-if-changed=build.rs");

    let invariants_dir = PathBuf::from("invariants");
    
    if !invariants_dir.exists() {
        eprintln!("Warning: invariants/ directory not found, skipping DSL compilation");
        generate_empty_invariants();
        return;
    }

    let mut all_invariants: BTreeMap<String, InvariantDef> = BTreeMap::new();

    // Scan invariants/evm, invariants/solana, invariants/move
    for chain_dir in &["evm", "solana", "move"] {
        let chain_path = invariants_dir.join(chain_dir);
        
        if !chain_path.exists() {
            continue;
        }

        if let Ok(entries) = fs::read_dir(&chain_path) {
            for entry in entries.flatten() {
                let path = entry.path();
                
                if path.extension().map(|e| e == "sinv").unwrap_or(false) {
                    match parse_sinv_file(&path) {
                        Ok(inv) => {
                            all_invariants.insert(inv.id.clone(), inv);
                        }
                        Err(e) => {
                            eprintln!("{}", e);
                            std::process::exit(1);
                        }
                    }
                }
            }
        }
    }

    generate_rust_module(&all_invariants);
}

/// Parse a single .sinv file
fn parse_sinv_file(path: &PathBuf) -> Result<InvariantDef, String> {
    let content = fs::read_to_string(path)
        .map_err(|e| format!("{}:1: Failed to read file: {}", path.display(), e))?;

    let mut inv = InvariantDef::default();
    
    // Parse key = "value" format
    for (line_num, line) in content.lines().enumerate() {
        let line = line.trim();
        
        // Skip comments and empty lines
        if line.starts_with('#') || line.is_empty() {
            continue;
        }

        if let Some((key, value)) = line.split_once('=') {
            let key = key.trim();
            let value = value.trim().trim_matches('"').trim_matches('[').trim_matches(']');

            match key {
                "invariant" => inv.id = value.to_string(),
                "severity" => inv.severity = value.to_string(),
                "chain" => inv.chain = value.to_string(),
                "description" => inv.description = value.to_string(),
                "message" => inv.message = value.to_string(),
                _ => {} // Ignore unknown fields
            }
        }
    }

    // Validate required fields
    if inv.id.is_empty() {
        return Err(format!("{}:1: Missing required field: invariant", path.display()));
    }
    if inv.severity.is_empty() {
        return Err(format!("{}:1: Missing required field: severity", path.display()));
    }
    if inv.chain.is_empty() {
        return Err(format!("{}:1: Missing required field: chain", path.display()));
    }

    Ok(inv)
}

#[derive(Debug, Clone, Default)]
struct InvariantDef {
    id: String,
    severity: String,
    chain: String,
    description: String,
    message: String,
}

/// Generate the invariants.rs module
fn generate_rust_module(invariants: &BTreeMap<String, InvariantDef>) {
    let mut rust_code = String::from(
        r#"// This file is auto-generated by build.rs from .sinv files.
// DO NOT EDIT MANUALLY.

use once_cell::sync::Lazy;
use std::collections::BTreeMap;

/// Compiled invariant definition
#[derive(Debug, Clone)]
pub struct CompiledInvariant {
    pub id: &'static str,
    pub severity: &'static str,
    pub chain: &'static str,
    pub description: &'static str,
    pub message: &'static str,
}

/// Global registry of all compiled invariants
pub static INVARIANT_REGISTRY: Lazy<BTreeMap<&'static str, CompiledInvariant>> = 
    Lazy::new(|| {
        let mut map = BTreeMap::new();
"#
    );

    for (_, inv) in invariants.iter() {
        let id = &inv.id;
        let severity = &inv.severity;
        let chain = &inv.chain;
        let description = &inv.description;
        let message = &inv.message;

        rust_code.push_str(&format!(
            r#"
        map.insert("{id}", CompiledInvariant {{
            id: "{id}",
            severity: "{severity}",
            chain: "{chain}",
            description: "{description}",
            message: "{message}",
        }});
"#
        ));
    }

    rust_code.push_str(
        r#"
        map
    });

/// Get an invariant by ID
pub fn get_invariant(id: &str) -> Option<&'static CompiledInvariant> {
    INVARIANT_REGISTRY.get(id).map(|i| i)
}

/// List all invariants for a chain
pub fn invariants_for_chain(chain: &str) -> Vec<&'static CompiledInvariant> {
    INVARIANT_REGISTRY
        .values()
        .filter(|inv| inv.chain == chain)
        .collect()
}

/// Count total invariants
pub fn invariant_count() -> usize {
    INVARIANT_REGISTRY.len()
}
"#
    );

    // Create generated directory if needed
    let out_dir = PathBuf::from("crates/core/src/generated");
    fs::create_dir_all(&out_dir).ok();

    let out_path = out_dir.join("invariants.rs");
    fs::write(&out_path, rust_code)
        .expect("Failed to write generated invariants.rs");

    println!("cargo:rustc-env=INVARIANTS_GENERATED=1");
}

fn generate_empty_invariants() {
    let out_dir = PathBuf::from("crates/core/src/generated");
    fs::create_dir_all(&out_dir).ok();

    let out_path = out_dir.join("invariants.rs");
    let empty_code = r#"// Empty invariant registry (no .sinv files found)
use once_cell::sync::Lazy;
use std::collections::BTreeMap;

#[derive(Debug, Clone)]
pub struct CompiledInvariant {
    pub id: &'static str,
    pub severity: &'static str,
    pub chain: &'static str,
    pub description: &'static str,
    pub message: &'static str,
}

pub static INVARIANT_REGISTRY: Lazy<BTreeMap<&'static str, CompiledInvariant>> = 
    Lazy::new(|| BTreeMap::new());

pub fn get_invariant(id: &str) -> Option<&'static CompiledInvariant> {
    INVARIANT_REGISTRY.get(id).map(|i| i)
}

pub fn invariants_for_chain(chain: &str) -> Vec<&'static CompiledInvariant> {
    vec![]
}

pub fn invariant_count() -> usize {
    0
}
"#;
    
    fs::write(&out_path, empty_code).ok();
}
