#!/usr/bin/env python3
"""emit_harness.py — emit an Echidna/Medusa property harness for a contract.

Truent's own fuzzer (`truent fuzz --dynamic`) needs no harness and no external
toolchain — it auto-detects invariants and shrinks a violation to a minimal
PoC in one binary. This generator exists for interop: teams standardized on
Echidna or Medusa can get a ready property suite for the SAME invariant shapes
Truent checks, so Truent is a strict superset of a harness generator, not a
replacement that locks you in.

Given a target contract + the invariant shapes to assert, it writes:
  - <out>/TruentHarness.sol   — an Echidna/Medusa property contract
  - <out>/medusa.json         — a runnable Medusa config
  - <out>/echidna.yaml        — a runnable Echidna config

Usage:
  emit_harness.py --contract Vault --path src/Vault.sol \
      --props conservation,supply-monotonic --actors 3 --out test/fizz
"""
import argparse
import json
import os

PROP_LIBRARY = {
    # name -> (property function body lines)
    "conservation": (
        "echidna_conservation",
        "sum(balanceOf(actor)) over the actor set equals totalSupply()",
        [
            "uint256 sum;",
            "for (uint256 i = 0; i < actors.length; i++) {",
            "    sum += target.balanceOf(actors[i]);",
            "}",
            "return sum == target.totalSupply();",
        ],
    ),
    "supply-monotonic": (
        "echidna_supply_monotonic",
        "totalSupply() never decreases across the campaign",
        [
            "return target.totalSupply() >= _lastSupply;",
        ],
    ),
    "owner-stable": (
        "echidna_owner_unchanged_by_others",
        "owner() only changes via the owner (no unprivileged takeover)",
        [
            "return target.owner() == _expectedOwner;",
        ],
    ),
}


def gen_solidity(contract, path, props, actors):
    rel = os.path.relpath(path)
    lines = []
    lines.append("// SPDX-License-Identifier: MIT")
    lines.append("pragma solidity ^0.8.0;")
    lines.append("")
    lines.append(f'import {{{contract}}} from "{rel}";')
    lines.append("")
    lines.append("/// @notice Echidna/Medusa property harness generated by Truent.")
    lines.append("/// Assertions mirror the invariant shapes Truent's native fuzzer")
    lines.append("/// (`truent fuzz --dynamic`) checks automatically. Wire the")
    lines.append("/// constructor deployment to your real setup where marked TODO.")
    lines.append(f"contract TruentHarness {{")
    lines.append(f"    {contract} internal target;")
    lines.append(f"    address[{actors}] internal actors;")
    lines.append("    uint256 internal _lastSupply;")
    lines.append("    address internal _expectedOwner;")
    lines.append("")
    lines.append("    constructor() {")
    lines.append("        // TODO: deploy `target` the way your project does, and")
    lines.append("        // seed the actor set. Echidna/Medusa will call target's")
    lines.append("        // external functions from these senders.")
    lines.append(f"        target = new {contract}();")
    for i in range(actors):
        lines.append(f"        actors[{i}] = address(uint160(0x1000 + {i}));")
    lines.append("        _lastSupply = target.totalSupply();")
    lines.append("        _expectedOwner = address(this);")
    lines.append("    }")
    lines.append("")
    # a bookkeeping hook so monotonic property has a baseline to compare
    lines.append("    function _sync() internal {")
    lines.append("        uint256 s = target.totalSupply();")
    lines.append("        if (s > _lastSupply) _lastSupply = s;")
    lines.append("    }")
    lines.append("")
    for key in props:
        entry = PROP_LIBRARY.get(key)
        if not entry:
            lines.append(f"    // (unknown property '{key}' skipped)")
            continue
        fn, desc, body = entry
        lines.append(f"    /// @notice {desc}")
        lines.append(f"    function {fn}() public view returns (bool) {{")
        for b in body:
            lines.append(f"        {b}")
        lines.append("    }")
        lines.append("")
    lines.append("}")
    return "\n".join(lines) + "\n"


def gen_medusa(out_contract="TruentHarness"):
    return json.dumps({
        "fuzzing": {
            "workers": 8,
            "testLimit": 100000,
            "callSequenceLength": 100,
            "targetContracts": [out_contract],
        },
        "testing": {
            "propertyTesting": {"enabled": True, "testPrefixes": ["echidna_"]},
            "assertionTesting": {"enabled": True},
        },
    }, indent=2) + "\n"


def gen_echidna(out_contract="TruentHarness"):
    # Echidna reads YAML; keep it minimal + valid.
    return (
        "testMode: property\n"
        "testLimit: 100000\n"
        "seqLen: 100\n"
        f"# run: echidna <path> --contract {out_contract} --config echidna.yaml\n"
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--contract", required=True)
    ap.add_argument("--path", required=True, help="path to the target contract source")
    ap.add_argument("--props", default="conservation,supply-monotonic")
    ap.add_argument("--actors", type=int, default=3)
    ap.add_argument("--out", default="test/fizz")
    a = ap.parse_args()

    props = [p.strip() for p in a.props.split(",") if p.strip()]
    os.makedirs(a.out, exist_ok=True)

    sol = gen_solidity(a.contract, a.path, props, a.actors)
    with open(os.path.join(a.out, "TruentHarness.sol"), "w") as fh:
        fh.write(sol)
    with open(os.path.join(a.out, "medusa.json"), "w") as fh:
        fh.write(gen_medusa())
    with open(os.path.join(a.out, "echidna.yaml"), "w") as fh:
        fh.write(gen_echidna())

    print(f"Wrote {a.out}/TruentHarness.sol ({len(props)} properties), medusa.json, echidna.yaml")
    print("Run natively (recommended, no toolchain):")
    print(f"  truent fuzz {a.path} --dynamic --chain evm")
    print("Or with the emitted harness:")
    print(f"  medusa fuzz --config {a.out}/medusa.json")
    print(f"  echidna {a.out}/TruentHarness.sol --contract TruentHarness --config {a.out}/echidna.yaml")


if __name__ == "__main__":
    main()
