[package]
name = "truent-solana-macro"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

description = "Truent: Procedural macros for Truent Solana code generation and security constraint injection."

keywords = ["truent", "solana", "security", "smart-contracts", "macros"]
categories = ["development-tools", "development-tools::testing"]
readme = "README.md"
documentation = "https://docs.rs/truent-solana-macro"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }

[dev-dependencies]
