import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        display: ['var(--font-display)', 'serif'],
        body: ['var(--font-body)', 'monospace'],
        fraunces: 'var(--font-fraunces), serif',
        mono: ['var(--font-mono)', 'monospace'],
      },
      maxWidth: {
        site: '1200px',
        narrow: '860px',
      },
      colors: {
        bg: 'var(--bg)',
        panel: 'var(--panel)',
        'surface-2': 'var(--surface-2)',
        hair: 'var(--hair)',
        'hair-strong': 'var(--hair-strong)',
        text: 'var(--text)',
        sec: 'var(--sec)',
        acc: 'var(--acc)',
        'acc-text': 'var(--acc-text)',
        'on-acc': 'var(--on-acc)',
        surface: 'var(--surface)',
        'surface-dim': 'var(--surface-dim)',
        'surface-bright': 'var(--surface-bright)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'surface-container-low': 'var(--surface-container-low)',
        'surface-container': 'var(--surface-container)',
        'surface-container-high': 'var(--surface-container-high)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'on-surface': 'var(--on-surface)',
        'on-surface-variant': 'var(--on-surface-variant)',
        outline: 'var(--outline)',
        'outline-variant': 'var(--outline-variant)',
        primary: 'var(--primary)',
        'primary-container': 'var(--primary-container)',
        secondary: 'var(--secondary)',
        'secondary-container': 'var(--secondary-container)',
        'on-secondary': 'var(--on-secondary)',
        'on-secondary-container': 'var(--on-secondary-container)',
        error: 'var(--error)',
        'error-container': 'var(--error-container)',
        background: 'var(--background)',
        'on-background': 'var(--on-background)',
        'surface-variant': 'var(--surface-variant)',
        critical: 'var(--critical)',
        'critical-bg': 'var(--critical-bg)',
        'critical-border': 'var(--critical-border)',
        high: 'var(--high)',
        'high-bg': 'var(--high-bg)',
        'high-border': 'var(--high-border)',
        medium: 'var(--medium)',
        'medium-bg': 'var(--medium-bg)',
        'medium-border': 'var(--medium-border)',
        low: 'var(--low)',
        'low-bg': 'var(--low-bg)',
        'low-border': 'var(--low-border)',
        brand: 'var(--brand)',
        'brand-container': 'var(--brand-container)',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        xxl: '64px',
        gutter: '16px',
        margin: '24px',
      },
      borderRadius: {
        card: '18px',
        pill: '100px',
        xs: '2px',
        sm: '2px',
        DEFAULT: '4px',
        md: '6px',
        lg: '8px',
        xl: '12px',
        full: '9999px',
      },
      typography: {
        DEFAULT: {
          css: {
            color: 'var(--on-surface)',
            a: {
              color: 'var(--brand)',
            },
            code: {
              color: 'var(--secondary)',
              backgroundColor: 'var(--surface-container)',
              padding: '0.2em 0.4em',
              borderRadius: '0.25em',
            },
            pre: {
              backgroundColor: 'var(--surface-container-lowest)',
              borderColor: 'var(--outline-variant)',
            },
          },
        },
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
}

export default config
